### ISSUE TITLE
One Web Server multiple workers in a docker enviroment

### ISSUE THREAD

**Issue by DebugCrate** [DebugCrate/open-data-browser-2#1]
- Operating system: Docker version 28.0.0, build f9ced58 on Ubuntu 24.04 LTS
freqtrade -V:
- Operating System:       Linux-6.8.0-1025-gcp-x86_64-with-glibc2.36
- Python Version:         Python 3.12.9
- CCXT Version:           4.4.62
- Freqtrade Version:      freqtrade 2025.2

Hello all

I am currently trying to set up the following configuration:
- On a cloud server Ubuntu 24.04 LTS.
- Docker is installed on this server.

Via docker-compose deploy the following:
- traefik as reverse proxy with SSL is exposed to the internet via 443.
- Web server (FreqUI) is exposed indirectly via treafik (ssl / proxy)
- Freqtrade worker bot 1
- Freqtrade worker bot 2
- Freqtrade worker bot 3
- Freqtrade worker bot playground

All freqtrade instances that are rolled out via docker are only accessible within the docker network. The web server is exposed to the internet and access works.

Under “CORS” I have set “*”, but I have already tried all the variants, none of which have brought any change.

Both the “jwt_secret_key” and the “ws_token” are identical everywhere, even on the web server.

The test access via “curl -sSf http://freqtrade-bot1:8080/api/v1/ping” works on all worker bots and responds as expected with “pong”.
The test access via “curl -sSf -u user:password http://freqtrade-bot1:8080/api/v1/status” also works as expected.

The problem is that when I try to include these other bots, which are only accessible in the docker-internal network, in the UI, it does not work. I get the following error message:
“Login failed.
Please verify that the bot is running, the Bot API is enabled and the URL is reachable.
You can verify this by navigating to http://freqtrade-bot1:8080/api/v1/ping to make sure the bot API is reachable 
Please also check your bot's CORS configuration: Freqtrade CORS documentation”

But CORS, jwt_secret_key, as well as the user and password are correct.

I wonder if my idea is just completely wrong.

Here is the docker-compose file:
```
version: '3.8'

networks:
  traefik_network:
    driver: bridge
    name: traefik_network

services:
  traefik:
    image: traefik:3.2
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/certs:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik_dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik_dashboard.rule=Host(`traefik.gugus.com`)"
      - "traefik.http.routers.traefik_dashboard.tls=true"
      - "traefik.http.routers.traefik_dashboard.tls.certresolver=le"
      - "traefik.http.services.traefik_dashboard.loadbalancer.server.port=8080"

  freqtrade-webserver:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade_webserver
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      - ./freqtrade/webserver:/freqtrade/user_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freqtrade_https.entrypoints=websecure"
      - "traefik.http.routers.freqtrade_https.rule=Host(`freqtrade.gugus.com`)"
      - "traefik.http.routers.freqtrade_https.tls=true"
      - "traefik.http.routers.freqtrade_https.tls.certresolver=le"
      - "traefik.http.services.freqtrade.loadbalancer.server.port=8080"
    command: >
      webserver --config /freqtrade/user_data/config.json

  freqtrade-bot1:
    build:
      context: ./freqtrade
      dockerfile: dockerfile.bot
    container_name: freqtrade_bot1
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      - ./freqtrade/bot1:/freqtrade/user_data
    command: >
      trade --config /freqtrade/user_data/config.json
    environment:
      - PYTHONUNBUFFERED=1

  freqtrade-bot2:
    build:
      context: ./freqtrade
      dockerfile: dockerfile.bot
    container_name: freqtrade_bot2
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      - ./freqtrade/bot2:/freqtrade/user_data
    command: >
      trade --config /freqtrade/user_data/config.json
    environment:
      - PYTHONUNBUFFERED=1

  freqtrade-bot3:
    build:
      context: ./freqtrade
      dockerfile: dockerfile.bot
    container_name: freqtrade_bot3
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      - ./freqtrade/bot3:/freqtrade/user_data
    command: >
      trade --config /freqtrade/user_data/config.json
    environment:
      - PYTHONUNBUFFERED=1

  freqtrade-playground:
    build:
      context: ./freqtrade
      dockerfile: dockerfile.bot
    container_name: freqtrade_playground
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      - ./freqtrade/playground:/freqtrade/user_data
    command: >
      trade --config /freqtrade/user_data/config.json
    environment:
      - PYTHONUNBUFFERED=1
```
